modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "ftbpc"
version = "${version}"
displayName = "FTB Pack Companion"
authors = "FTB Team"
description = '''
A Modpack developers best friend
'''
#logoFile = ""

[[dependencies.ftbpc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbpc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbpc]]
modId = "architectury"
mandatory = true
versionRange = "[4.10.86,)"
ordering = "AFTER"
side = "BOTH"
