modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "ftbpc"
version = "${version}"
displayName = "FTB Pack Companion"
authors = "FTB Team"
description = '''
A Modpack developers best friend
'''
#logoFile = ""

[[dependencies.ftbpc]]
modId = "neoforge"
required = true
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbpc]]
modId = "minecraft"
required = true
versionRange = "[1.20.4,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbpc]]
modId = "architectury"
required = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ftbpc-common.mixins.json"

[[mixins]]
config = "ftbpc.mixins.json"
